### ISSUE TITLE
Issue-refactor: more quality of life changes to the overall package

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/call-api#10]
Automated Review Comments
Issues in eslint.config.mjs:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/createFetchClient.ts:
  - (39, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (171, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
Issues in src/index.ts:
  - (8, 'Line exceeds 80 characters')
Issues in src/lib/fetch-utils.ts:
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
Issues in src/lib/regular-utils.ts:
  - (39, 'Line exceeds 80 characters')
Issues in src/lib/type-helpers/global.ts:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
Issues in src/lib/type-helpers/typeof.ts:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in src/types.ts:
  - (2, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
