### ISSUE TITLE
Issue-chore: fixes to lint staged madness

### ISSUE THREAD

**Issue by ishida0415** [ishida0415/call-api#8]
Automated Review Comments
Issues in lint-staged.config.mjs:
  - (3, 'Hardcoded string found')
Issues in src/utils/type-helpers.ts:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
